version: '3.5'

services:
  appcom:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: appcom
    depends_on:
      - dbcom
    ports:
      - "8081:8081"
    networks:
      - app-network

  dbcom:
    restart: always
    image: postgres:latest
    container_name: dbcom
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_PASSWORD=kataku

    ports:
      - 5433:5432
    expose:
      - 5433
    networks:
      - app-network

  adminercom:
    image: adminer
    container_name: adminercom
    restart: always
    ports:
      - 8082:8082
    expose:
      - 8082
    networks:
      - app-network

volumes:
  postgres:
    driver: local

networks:
  app-network:
    driver: bridge
